POST http://localhost:8080/login 
Content-Type: application/json

{
   "id": "abcde12345", "password": "12345"
}


###

GET http://localhost:8080/login/abcde12345
Content-Type: application/json

###

POST http://localhost:8080/logout 
Content-Type: application/json

###

POST http://localhost:8888/cust 
Content-Type: application/json

{
   "cust_edrpou": 55555555, 
   "cust_itn": 55555555,
   "cust_name": "sosiska",
   "cust_phone": "824982983472",
   "cust_region": "test region",
   "cust_city": "test city", 
   "cust_street": "test street", 
   "cust_building": "test build",
   "cust_email": "email@wqeuy.com", 
   "cust_acc": "6sqq7g217e12e6ey78t1g2d81y2b78", 
   "cust_debt": 1
}

###

POST http://localhost:8888/order
Content-Type: application/json

{
   "ord_id" : 6666,
   "ord_date" : "2020-04-16",
   "ord_notes" : "",
   "cust_edrpou" : 44444444,
   "order_lines" : [
      {
         "prod_cd" : 222234,
         "line_amount" : 60
      },
      {
         "prod_cd" : 333112,
         "line_amount" : 40
      }
   ]
}