PUT http://localhost:8888/prod/444444
Content-Type: application/json

{
    "prod_name": "SECOND TEST",
    "prod_unit": "cm",
    "man_id": 2,
    "categs": [2,3,4]
}

###

GET http://localhost:8888/prod/444444
Content-Type: application/json
